// <auto-generated />
using AdministradorChatBot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdministradorChatBot.Migrations
{
    [DbContext(typeof(ChatbotDbContext))]
    [Migration("20250525192741_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdministradorChatBot.Models.Chatbot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Chatbots__3214EC07B9364CBD");

                    b.HasIndex("UserId");

                    b.ToTable("Chatbots");
                });

            modelBuilder.Entity("AdministradorChatBot.Models.ChatbotKeyword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatbotId")
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__ChatbotK__3214EC07C8C84E66");

                    b.HasIndex("ChatbotId");

                    b.ToTable("ChatbotKeywords");
                });

            modelBuilder.Entity("AdministradorChatBot.Models.ChatbotResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KeywordId")
                        .HasColumnType("int");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__ChatbotR__3214EC072D396CC2");

                    b.HasIndex("KeywordId");

                    b.ToTable("ChatbotResponses");
                });

            modelBuilder.Entity("AdministradorChatBot.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07DF705DF0");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AdministradorChatBot.Models.Chatbot", b =>
                {
                    b.HasOne("AdministradorChatBot.Models.User", "User")
                        .WithMany("Chatbots")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Chatbots__UserId__4BAC3F29");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AdministradorChatBot.Models.ChatbotKeyword", b =>
                {
                    b.HasOne("AdministradorChatBot.Models.Chatbot", "Chatbot")
                        .WithMany("ChatbotKeywords")
                        .HasForeignKey("ChatbotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChatbotKe__Chatb__4E88ABD4");

                    b.Navigation("Chatbot");
                });

            modelBuilder.Entity("AdministradorChatBot.Models.ChatbotResponse", b =>
                {
                    b.HasOne("AdministradorChatBot.Models.ChatbotKeyword", "Keyword")
                        .WithMany("ChatbotResponses")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ChatbotRe__Keywo__5165187F");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("AdministradorChatBot.Models.Chatbot", b =>
                {
                    b.Navigation("ChatbotKeywords");
                });

            modelBuilder.Entity("AdministradorChatBot.Models.ChatbotKeyword", b =>
                {
                    b.Navigation("ChatbotResponses");
                });

            modelBuilder.Entity("AdministradorChatBot.Models.User", b =>
                {
                    b.Navigation("Chatbots");
                });
#pragma warning restore 612, 618
        }
    }
}
